### ISSUE TITLE
Vanilla Mixin-Related Crash on startup with Et Futurum Requiem 

### ISSUE THREAD

**Issue by SilearFlare** [FalsePattern/LagGogglesLegacy#1]
A pretty specific, but deadly issue: the game crashes at startup due to a critical problem in common.vanilla.MixinEventBus. 

I've checked this multiple times, all it's required to reproduce this is to have Lag Goggles, FalsepatternLib, Et Futurum Requiem and SpongeMixins Loader. I suspect any other mod that tangles with that mixin class would have the same effect.

Crashlog here
https://paste.ee/p/aIKj6

The issue might be related to how in 1.7, many mods' transformers assume they only get run once, so a mixin class merely getting preprocessed causes a crash (because transformers are run an additional time during preprocessing).

Thank you in advance with any help on the subject, I extensively use 1.7 and I've always missed the sheer convenience of the lag goggles mod on this version, cheers for the work!

**Comment by makamys** [comment]
I looked at the class loading trace with `-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true`. What happens is that while [Et Futurum's Mixin config plugin](https://github.com/Roadhog360/Et-Futurum-Requiem/blob/3a700c86b1ecfb6d0e0b7deca9c4cbcfd2f1761a/src/main/java/ganymedes01/etfuturum/EtFuturumMixinPlugin.java) (which runs in the DEFAULT phase) loads its config, it also loads Forge classes including EventBus. Lag Goggles's mixins are processed afterwards, by which time it's too late.

I believe the correct fix is to move your mixins targetting Forge classes to the PREINIT phase.

**Comment by FalsePattern** [comment]
Should be fixed in 4.12.2

**Comment by SilearFlare** [comment]
I'm sorry, but the game still crashes at startup with the same setup (only Et Futurum added) after updating to 4.12.2, this time with a different error log, something about Mixin re-entrance, because of "multiple constructors".

Here's the log: https://paste.ee/p/CGS3B

**Comment by makamys** [comment]
It turns out you can't have mixins to classes referenced by Mixin config plugins, even if they only run in a later phase. So moving the Forge mixins to pre-init didn't solve the issue after all.
I removed the Forge class reference from Et Futurum that caused the issue, now it works fine even with LagGogglesLegacy 4.12.0. Other mixin mods seem to work fine too, so maybe this was just an Et Futurum issue.

**Comment by SilearFlare** [comment]
Confirmed both mods to be working with the latest snapshot of et futurum! :fireworks: 
The log still mentions the multiple constructors line, but it seems to be largely irrelevant.
I think I can close this one, thank you both!
